//! Scan session — per-run state, findings, and statistics.
//!
//! A [`ScanSession`] is created once per invocation of Secret Squirrel and
//! tracks:
//!
//! - **Configuration** — the full [`SquirrelConfig`] for this scan.
//! - **HMAC nonce** — 32 random bytes generated at session start.  Used to
//!   derive [`Finding::secret_hash`] values via HMAC-SHA256.  The nonce is
//!   per-session so hashes are stable within a single run but cannot be
//!   correlated across runs without the nonce.
//! - **Findings** — accumulated [`Finding`]s, deduplicated on finalise.
//! - **Stats** — aggregate counters for files, bytes, GPU/CPU dispatches, etc.
//!
//! # Lifecycle
//!
//! ```text
//! ScanSession::new(config)
//!     → scan sources (add_finding per detection)
//!     → session.finalize()        ← dedup + sort
//!     → session.findings          ← iterate for reporting
//! ```

use chrono::{DateTime, Utc};
use rand::RngCore;
use serde::{Deserialize, Serialize};
use std::collections::HashSet;
use tracing::debug;

use crate::config::SquirrelConfig;
use crate::types::{Finding, Severity};

// ============================================================================
// ScanStats
// ============================================================================

/// Aggregate statistics accumulated during a scan session.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ScanStats {
    /// Number of files (or virtual fragments) fully processed.
    pub files_scanned: u64,
    /// Total bytes ingested across all fragments.
    pub bytes_scanned: u64,
    /// Total number of findings (before deduplication).
    pub findings_count: u64,
    /// Number of GPU compute dispatches issued.
    pub gpu_dispatches: u64,
    /// Number of CPU compute dispatches issued.
    pub cpu_dispatches: u64,
    /// Wall-clock duration of the scan (milliseconds).
    pub duration_ms: u64,
    /// UTC timestamp when the session was created.
    pub started_at: DateTime<Utc>,
}

impl ScanStats {
    /// Create a new stats struct stamped with the current UTC time.
    fn new() -> Self {
        Self {
            started_at: Utc::now(),
            ..Default::default()
        }
    }

    /// Record that a file of `bytes` was scanned using the given backend.
    pub fn record_file(&mut self, bytes: u64, used_gpu: bool) {
        self.files_scanned += 1;
        self.bytes_scanned += bytes;
        if used_gpu {
            self.gpu_dispatches += 1;
        } else {
            self.cpu_dispatches += 1;
        }
    }

    /// Finalise the duration field using the current time minus `started_at`.
    pub fn seal(&mut self) {
        let elapsed = Utc::now()
            .signed_duration_since(self.started_at)
            .num_milliseconds();
        self.duration_ms = elapsed.max(0) as u64;
    }

    /// Return total dispatches (GPU + CPU).
    pub fn total_dispatches(&self) -> u64 {
        self.gpu_dispatches + self.cpu_dispatches
    }

    /// Return the GPU utilisation ratio (0.0 – 1.0).
    pub fn gpu_utilisation(&self) -> f64 {
        let total = self.total_dispatches();
        if total == 0 {
            0.0
        } else {
            self.gpu_dispatches as f64 / total as f64
        }
    }
}

// ============================================================================
// ScanSession
// ============================================================================

/// Per-scan session state.
///
/// # Security
///
/// The `nonce` field holds 32 cryptographically random bytes generated by
/// `rand::thread_rng()`.  It is used as the HMAC key for
/// [`crate::types::hash_secret`].  The nonce is **not** persisted — it is
/// regenerated each time a new session is created, so secret hashes cannot
/// be correlated across independent scans.
pub struct ScanSession {
    /// Configuration active for this scan.
    pub config: SquirrelConfig,
    /// 32-byte HMAC nonce (per-session, random).
    pub nonce: Vec<u8>,
    /// Accumulated findings (not yet deduplicated).
    pub findings: Vec<Finding>,
    /// Scan statistics.
    pub stats: ScanStats,
}

impl std::fmt::Debug for ScanSession {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ScanSession")
            .field("findings", &self.findings.len())
            .field("stats", &self.stats)
            .finish_non_exhaustive()
    }
}

impl ScanSession {
    /// Create a new session with a freshly generated HMAC nonce.
    pub fn new(config: SquirrelConfig) -> Self {
        // Generate 32 cryptographically random bytes.
        let mut nonce = vec![0u8; 32];
        rand::thread_rng().fill_bytes(&mut nonce);

        debug!("ScanSession created with fresh 32-byte nonce");

        Self {
            config,
            nonce,
            findings: Vec::new(),
            stats: ScanStats::new(),
        }
    }

    /// Append a [`Finding`] to the session.
    ///
    /// The finding is stored verbatim; call [`finalize`] to sort and deduplicate.
    pub fn add_finding(&mut self, finding: Finding) {
        self.stats.findings_count += 1;
        self.findings.push(finding);
    }

    /// Remove exact duplicates identified by `(rule_id, secret_hash, path)`.
    ///
    /// The first occurrence of each unique triple is kept; subsequent
    /// duplicates are discarded.  Call this before generating a report.
    pub fn deduplicate_findings(&mut self) {
        let mut seen: HashSet<(String, String, String)> = HashSet::new();
        self.findings.retain(|f| {
            let key = (
                f.rule_id.clone(),
                f.secret_hash.clone(),
                f.location.path.clone(),
            );
            seen.insert(key)
        });

        debug!(
            retained = self.findings.len(),
            "Deduplication complete"
        );
    }

    /// Sort findings by severity (descending) then confidence (descending),
    /// and apply deduplication.
    ///
    /// Call once after all fragments have been processed.
    pub fn finalize(&mut self) {
        self.deduplicate_findings();

        // Sort: highest severity first, then highest confidence.
        self.findings.sort_by(|a, b| {
            b.severity
                .cmp(&a.severity)
                .then_with(|| {
                    b.score
                        .confidence
                        .partial_cmp(&a.score.confidence)
                        .unwrap_or(std::cmp::Ordering::Equal)
                })
        });

        self.stats.seal();

        debug!(
            findings = self.findings.len(),
            duration_ms = self.stats.duration_ms,
            "ScanSession finalised"
        );
    }

    /// Return findings at or above the configured severity threshold.
    pub fn filtered_findings(&self) -> impl Iterator<Item = &Finding> {
        let threshold = self.config.scan.severity_threshold;
        self.findings.iter().filter(move |f| f.severity >= threshold)
    }

    /// Mutable iterator over all findings — used for post-scan annotation
    /// (cross-file correlation, validation results).
    pub fn findings_mut(&mut self) -> impl Iterator<Item = &mut Finding> {
        self.findings.iter_mut()
    }

    /// Return the number of unique findings after deduplication.
    pub fn unique_finding_count(&self) -> usize {
        self.findings.len()
    }

    /// Return `true` if any finding meets or exceeds the given severity.
    pub fn has_findings_at_or_above(&self, severity: Severity) -> bool {
        self.findings.iter().any(|f| f.severity >= severity)
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::SquirrelConfig;
    use crate::types::{FusedScore, Location, RedactedString, Severity};
    use chrono::Utc;

    fn dummy_finding(rule_id: &str, path: &str, severity: Severity, confidence: f64) -> Finding {
        Finding {
            id: uuid_stub(rule_id, path),
            rule_id: rule_id.to_string(),
            description: format!("Test finding for {rule_id}"),
            secret: RedactedString::new("AKIAIOSFODNN7EXAMPLE".to_string()),
            secret_hash: format!("{rule_id}:{path}:hash"),
            match_context: String::new(),
            location: Location {
                path: path.to_string(),
                start_line: 1,
                end_line: 1,
                start_col: 0,
                end_col: 20,
                byte_offset: 0,
            },
            score: FusedScore {
                confidence,
                entropy: 0.5,
                proximity: 0.5,
                tristream: 0.5,
                pattern: 0.5,
                markov: 0.5,
                cnn_score: None,
                ast_adjustment: None,
            },
            severity,
            chain: None,
            validation: None,
            remediation: None,
            detected_at: Utc::now(), encoding_chain: None,
        }
    }

    /// Deterministic stub ID for testing.
    fn uuid_stub(rule: &str, path: &str) -> String {
        format!("{rule}_{path}")
    }

    #[test]
    fn test_new_session_generates_nonce() {
        let config = SquirrelConfig::default();
        let session = ScanSession::new(config);
        assert_eq!(session.nonce.len(), 32);
        assert_ne!(session.nonce, vec![0u8; 32], "Nonce should be random");
    }

    #[test]
    fn test_nonces_differ_across_sessions() {
        let s1 = ScanSession::new(SquirrelConfig::default());
        let s2 = ScanSession::new(SquirrelConfig::default());
        assert_ne!(
            s1.nonce, s2.nonce,
            "Each session should have a unique nonce"
        );
    }

    #[test]
    fn test_add_finding_increments_count() {
        let mut session = ScanSession::new(SquirrelConfig::default());
        assert_eq!(session.stats.findings_count, 0);
        session.add_finding(dummy_finding("aws-access-key", "config.env", Severity::High, 0.9));
        assert_eq!(session.stats.findings_count, 1);
        assert_eq!(session.findings.len(), 1);
    }

    #[test]
    fn test_deduplicate_removes_exact_duplicates() {
        let mut session = ScanSession::new(SquirrelConfig::default());

        let f1 = dummy_finding("rule-a", "file.py", Severity::High, 0.9);
        let f2 = dummy_finding("rule-a", "file.py", Severity::High, 0.9); // duplicate
        let f3 = dummy_finding("rule-b", "file.py", Severity::Medium, 0.6); // different rule

        session.add_finding(f1);
        session.add_finding(f2);
        session.add_finding(f3);

        assert_eq!(session.findings.len(), 3);
        session.deduplicate_findings();
        // f1 and f2 share (rule_id, secret_hash, path) → one removed
        assert_eq!(session.findings.len(), 2);
    }

    #[test]
    fn test_finalize_sorts_by_severity_desc() {
        let mut session = ScanSession::new(SquirrelConfig::default());

        session.add_finding(dummy_finding("rule-low", "a.py", Severity::Low, 0.6));
        session.add_finding(dummy_finding("rule-critical", "b.py", Severity::Critical, 0.95));
        session.add_finding(dummy_finding("rule-medium", "c.py", Severity::Medium, 0.7));

        session.finalize();

        assert_eq!(session.findings[0].severity, Severity::Critical);
        assert_eq!(session.findings[1].severity, Severity::Medium);
        assert_eq!(session.findings[2].severity, Severity::Low);
    }

    #[test]
    fn test_finalize_sorts_by_confidence_within_severity() {
        let mut session = ScanSession::new(SquirrelConfig::default());

        session.add_finding(dummy_finding("rule-a", "a.py", Severity::High, 0.6));
        session.add_finding(dummy_finding("rule-b", "b.py", Severity::High, 0.95));

        session.finalize();

        // Higher confidence should come first.
        assert!(
            session.findings[0].score.confidence >= session.findings[1].score.confidence,
            "Findings should be sorted by confidence descending"
        );
    }

    #[test]
    fn test_has_findings_at_or_above() {
        let mut session = ScanSession::new(SquirrelConfig::default());
        session.add_finding(dummy_finding("rule-a", "a.py", Severity::Medium, 0.7));

        assert!(session.has_findings_at_or_above(Severity::Low));
        assert!(session.has_findings_at_or_above(Severity::Medium));
        assert!(!session.has_findings_at_or_above(Severity::High));
    }

    #[test]
    fn test_stats_record_file() {
        let mut stats = ScanStats::new();
        stats.record_file(1024, false);
        stats.record_file(2048, true);

        assert_eq!(stats.files_scanned, 2);
        assert_eq!(stats.bytes_scanned, 3072);
        assert_eq!(stats.cpu_dispatches, 1);
        assert_eq!(stats.gpu_dispatches, 1);
        assert_eq!(stats.total_dispatches(), 2);
    }

    #[test]
    fn test_stats_gpu_utilisation() {
        let mut stats = ScanStats::new();
        stats.record_file(1000, true);
        stats.record_file(1000, true);
        stats.record_file(1000, false);

        let util = stats.gpu_utilisation();
        assert!(
            (util - 2.0 / 3.0).abs() < 0.001,
            "GPU utilisation should be 2/3"
        );
    }

    #[test]
    fn test_filtered_findings_respects_threshold() {
        let mut config = SquirrelConfig::default();
        config.scan.severity_threshold = Severity::High;

        let mut session = ScanSession::new(config);
        session.add_finding(dummy_finding("low", "a.py", Severity::Low, 0.5));
        session.add_finding(dummy_finding("high", "b.py", Severity::High, 0.9));
        session.add_finding(dummy_finding("critical", "c.py", Severity::Critical, 0.99));

        let visible: Vec<_> = session.filtered_findings().collect();
        assert_eq!(visible.len(), 2, "Only High and Critical should be visible");
    }
}
